### PR TITLE
Colorize icons by price within the range of all prices

### PR DESCRIPTION
**Pull request by nilsbraden**
Hi guys!

I liked the way this app displays all the necessary information but wanted to see at a glance how good a price compared to others is. So I added a few new icons and slightly changed colors, added the rating system to the Station object and calculated the rating based on a fixed percentage from lowest to highest price (10, 20, 30 and 40 Percent seemed a good choice for me and the stations close by).

Result looks like this:

Screenshot_20230930-105145_Gas Prices

Thank you for the nice app!

### CODE REVIEW

**Comment by woheller69** [comment]
Colors are used to show if stations are open or closed. This breaks the functionality

**Comment by woheller69** [comment]
Another idea might be to add a second marker for each station like a colored dot anchored at the top right of the station symbol.

**Comment by nilsbraden** [comment]
> Colors are used to show if stations are open or closed. This breaks the functionality

Ah yes, that's why I changed the colour for closed stations to a light grey. So it's still visible but not on the green-yellow-red range anymore.

**Comment by nilsbraden** [comment]
> Another idea might be to add a second marker for each station like a colored dot anchored at the top right of the station symbol.

That's also possible I guess, sure.

**Comment by woheller69** [comment]
I think we should add the dots

**Comment by woheller69** [comment]
I also would not add the rating to the database.
I would only calculate in CityAdapter when icons are put on the map

**Comment by woheller69** [comment]
And I would use fixed thresholds.

Up to
2ct green
4ct yellow
6ct orange
above red

**Comment by woheller69** [comment]
The size of the station symbol could be increased and a colored "€" be placed in the bottom part

**Comment by nilsbraden** [comment]
> I think we should add the dots

Not sure if I want to spend time on this though, I'm not convinced this adds any meaningful information. I don't really see why closed stations should be visible at all because their prices are outdated already by definition, they don't send updates so they could be ignored completely. So showing them in a different colour that has nothing to do with the price-range (e.g. grey) makes sense to me.

> I also would not add the rating to the database.
I would only calculate in CityAdapter when icons are put on the map

I chose this place beacuse there was no single point to add this. Even with adding it to the DBHelper I had to make sure the 
TK-API at
https://github.com/woheller69/spritpreise/blob/78d68b5c96a510846d1656e6bf5eb6477bc0b5af/app/src/main/java/org/woheller69/spritpreise/api/tankerkoenig/TKProcessHttpRequest.java#L88
doesn't return the data directly while also saving to DB. So an intermediate class to handle changes to the data in a central place would be helpful.

Heres a list of different places where the data is accessed:
2023-10-02 - 09-37-58 Uhr

> Up to
2ct green
4ct yellow
6ct orange
above red

This can be easily changed in CalculateStationRating().

**Pull request closed without merging**
